### ISSUE TITLE
Can't run prototyper ./myproject1  (windows)

### ISSUE THREAD

**Issue by Mihail12** [vitalik/django-prototyper#1]
After creating virtualenv and activate 
type: prototyper ./myproject1
raise:
(env) PS D:\project> prototyper new
Creating new project new
d:\project\env\scripts\python.exe: can't open file 'D:\project\env\Scripts\prototyper': [Errno 2] No such file or directory

**Comment by vitalik** [comment]
Hi @Mihail12 

Thank you for trying django prototyper
Unfortunately we did not do any tests under Windows yet..

What Windows version you use ?

**Comment by Mihail12** [comment]
Thanks for the answer.
Windows 10

**Comment by vitalik** [comment]
fixed in 0.1.17
